export const SET_ALL_LIVE_EVENTS = 'SET_ALL_LIVE_EVENTS';
export const SET_EVENT = 'SET_EVENT';
export const SET_MARKETS = 'SET_MARKETS';
export const SET_OUTCOMES = 'SET_OUTCOMES';
export const SET_ODDS_FORMAT = 'SET_ODDS_FORMAT';
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';
export const SET_ERROR = 'SET_ERROR';
